// <auto-generated />
using DZ3;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DZ3.Migrations
{
    [DbContext(typeof(CarContext))]
    partial class CarContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DZ3.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Information")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mark")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PublishYear")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Information = "general information\r\nBrand countryGermanyVehicle classENumber of doors4Number of seats5\r\nDimensions, mm\r\nLength4965Width1903Height1473Wheelbase2982Clearance128Front track width1626Rear track width1595Wheel size275/35/R20, 275/35/R20\r\nVolume and mass\r\nTrunk volume min / max, l530Volume of fuel tank, l68Curb weight, kg1940Gross weight, kg2440\r\nTransmission\r\nGearboxAutomaticNumber of gears8Drive typeall wheel drive\r\nSuspension and brakes\r\nFront suspension typeindependent, spring typeRear suspension typeindependent, spring typeFront brakesventilated discRear brakesventilated disc\r\nPerformance indicators\r\nMaximum speed, km/h250Acceleration to 100 km/h, s3.3Fuel consumption city/highway/combined, l15.2/8.7/10.8Fuel brand AI-95Emission classEuro 6CO2 emissions, g/km246\r\nEngine\r\nEngine typepetrolEngine locationfront, longitudinalEngine displacement, cm³4395Type of superchargingturbochargingMaximum power, hp/kW at rpm625/460 at 6000Maximum torque, N*m at rpm750 at 5800Cylinder arrangementV-shapedNumber of cylinders8Number of valves per cylinder4Engine power systemdirect injection (direct injection) Compression ratio10Cylinder diameter and piston stroke, mm88.3x89.0",
                            Mark = "Bmw",
                            Model = "M5 (F90)",
                            PublishYear = 2018
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
